### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3: character maps to <undefined>

### ISSUE THREAD

**Issue by joeribelis** [ethanfurman/dbf#26]
Looping over the records in the file straatnm.dbf gives UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3: character maps to <undefined>
you can download the dBASE files from this location : https://downloadagiv.blob.core.windows.net/crab-stratenlijst/dBASE/CRAB_stratenlijst.zip

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/administrator/.local/lib/python2.7/site-packages/dbf/__init__.py", line 3263, in __str__
    result.append("%3d - %-10s: %r" % (seq, field, self[field]))
  File "/home/administrator/.local/lib/python2.7/site-packages/dbf/__init__.py", line 3194, in __getitem__
    return self.__getattr__(item)
  File "/home/administrator/.local/lib/python2.7/site-packages/dbf/__init__.py", line 3161, in __getattr__
    value = self._retrieve_field_value(name)
  File "/home/administrator/.local/lib/python2.7/site-packages/dbf/__init__.py", line 3361, in _retrieve_field_value
    datum = retrieve(record_data, fielddef, self._meta.memo, self._meta.decoder)
  File "/home/administrator/.local/lib/python2.7/site-packages/dbf/__init__.py", line 4145, in retrieve_character
    data = fielddef[CLASS](decoder(data)[0])
  File "/usr/lib/python2.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3: character maps to <undefined>

**Comment by joeribelis** [comment]
codepage cp850 seems to help

**Comment by ethanfurman** [comment]
The behavior you are seeing is because of a bug in whichever application built the dbf file.  The dbf file format has a setting that states which code page should be used, with the default, `0`, meaning plain ascii -- unfortunately, many applications just leave that setting at the default, making it more difficult for other programs to properly interpret the contents of the file.
